.\"  -*- nroff -*-
.\"
.\" Author: Kevin Rosenberg <kevin@ctsim.org>
.\"
.\" $Id: ctsim.1,v 1.4 2002/05/03 10:45:52 kevin Exp $
.Dd May 2, 2002
.Dt ctsim 1
.Os
.Sh NAME
.Nm ctsim
.Nd A Graphical Computed Tomography Simulator
.Sh SYNOPSIS
.Nm ctsim files-to-open... [OPTIONS]
.Sh DESCRIPTION
.Pp 
.Nm 
is a graphical user interface to the various components of the CTSim package. The home for CTSim is http://www.ctsim.org.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl Fl version
Display version
.It Fl Fl help
Print a terse help message
.El
.Sh AUTHORS
Kevin Rosenberg, M.D. <kevin@ctsim.org>
.Sh HISTORY
CTSim was begun in 1983 using MS-DOS and an EGA display adapter. In
1999 it was ported to GNU/Linux and later ported to Microsoft Windows.
.Sh SEE ALSO
ifinfo (1), if1 (1), if2 (1), ifexport (1), phm2pj (1), phm2if (1), pj2if (1), pjinfo (1), pjrec (1)
