.\" -*- NROFF -*-
.\" 
.TH "linogram" "1" "" "Kevin Rosenberg" "Engineering"
.SH "NAME"
linogram \- Linogram gribddisplay for CTSIM
.SH "SYNOPSIS"
.B linogram [OPTIONS]
.SH "DESCRIPTION"
\fIlinogram\fP displays the grid used in linogram\-based scanning for 
the CTSim package. 
.SH "OPTIONS"
\fIlinogram\fP accepts the following options
.TP 12
.B \-\-version      Display version
.TP 12
.B \-\-help         Print a terse help message
.SH "AUTHORS"
Kevin Rosenberg, M.D. <kevin@ctsim.org>
.SH "HISTORY"
CTSim was begun in 1983 using MS\-DOS and an EGA display adapter. In
1999 it was ported to GNU/Linux and later ported to Microsoft Windows.
.SH "SEE ALSO"
.BR ctsim (1)
.BR ctsimtext (1)
.BR if1 (1)
.BR if2 (1)
.BR ifinfo (1)
.BR ifexport (1)
.BR phm2helix (1)
.BR phm2if (1)
.BR phm2pj (1)
.BR pj2if (1)
.BR pjHinterp (1)
.BR pjinfo (1)
.BR pjrec (1)
