.\" -*- NROFF -*-
.\" 
.TH "pjinfo" "1" "" "Kevin Rosenberg" "Engineering"
.SH "NAME"
pjinfo \- projection file information
.SH "SYNOPSIS"
.B pjinfo proj\-file [OPTIONS]
.SH "DESCRIPTION"
Displays information about a projection file.
.SH "OPTIONS"
.TP 
.B \-\-dump      
Dump all scan data
.TP 
.B \-\-version   
Print version
.TP 
.B \-\-help      
Print a terse help message
.SH "AUTHORS"
Kevin Rosenberg, M.D. <kevin@ctsim.org>
.SH "HISTORY"
CTSim was begun in 1983 using MS\-DOS and an EGA display adapter. In
1999 it was ported to GNU/Linux and later ported to Microsoft Windows.
.SH "SEE ALSO"
.BR ctsim (1)
.BR ctsimtext (1)
.BR if1 (1)
.BR if2 (1)
.BR ifinfo (1)
.BR linogram (1)
.BR phm2helix (1)
.BR phm2if (1)
.BR phm2pj (1)
.BR pj2if (1)
.BR pjHinterp (1)
.BR pjrec (1)
